### ISSUE TITLE
Identify or create AMI to develop with devcontainers

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#180]
## Image requirements

- Ubuntu (preferred)
- Docker Engine

## Tasks

- [ ] Explore Sage [AWS Image Repository](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/914882624/AWS+Image+Repository)
- [ ] Identify if an existing image can be used, if not:
- [ ] Explore how to add an image to Sage AWS Image Repository
  - Make sure the new AMI is available to team members in AWS

**Comment by tschaffter** [comment]
Related to #172

**Comment by tschaffter** [comment]
We are now using the AWS AMI with Docker pre-installed via Sage service catalog.
