### ISSUE TITLE
Explore how to split monolithic API into microservices 

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#212]
The goal is to learn more about modern standard practices around the architecture of backends with microservices.

## Tasks

- [x] Review https://github.com/reritom/Flask-Microservice-Tutorial
- [x] Read [Microservices – Authentication, and Authorization With Keycloak](https://javatodev.com/microservices-authentication-and-authorization-with-keycloak/)
- [x] Read [Microservices – User Service Implementation](https://javatodev.com/microservices-user-service-implementation/)
- [x] Read [Microservices – Setup API Gateway Using Spring Cloud Gateway](https://javatodev.com/microservices-setup-api-gateway-using-spring-cloud-gateway/)
- [x] Read [Microservices – Service Registration and Discovery With Spring Cloud Netflix Eureka](https://javatodev.com/microservices-service-registration-and-discovery-with-spring-cloud-netflix-eureka/)
- [x] #237
- [x] #236
- [x] #241

**Comment by tschaffter** [comment]
## https://javatodev.com/microservices-authentication-and-authorization-with-keycloak/

![image](https://user-images.githubusercontent.com/3056480/170619477-e58f4fa2-ddcc-49ff-b766-cef656a32902.png)

- Add API gateway
- Service registry?
- User service?

**Comment by tschaffter** [comment]
## https://javatodev.com/microservices-user-service-implementation/

- Create a service client for the User Service in KC
- User service
  - create user
  - read users with pagination
  - read user by auth id
  - read user by id and finally update user
- Eureka = [Service Registration and Discovery](https://spring.io/guides/gs/service-registration-and-discovery/)
  - `lb://` protocol used to point to User Service?

**Comment by tschaffter** [comment]
## [Microservices – Setup API Gateway Using Spring Cloud Gateway](https://javatodev.com/microservices-setup-api-gateway-using-spring-cloud-gateway/)

**Comment by tschaffter** [comment]
## [Microservices – Service Registration and Discovery With Spring Cloud Netflix Eureka](https://javatodev.com/microservices-service-registration-and-discovery-with-spring-cloud-netflix-eureka/)

> As you can imagine, discovery is the counterpart to registration from the point of view of clients. When a client wants to access a service, it must find out where the service is located (and other relevant information to perform the request).

- [Netflix Eureka](https://spring.io/projects/spring-cloud-netflix)
- two types of service discovery
  - Client-side service discovery
  - Server-side service discovery (most used discovery pattern)
- Setup Service Registry With Spring Cloud Netflix Eureka Server

### Related tasks

- Setup Service Registry with Spring Cloud Netflix Eureka Server
