### ISSUE TITLE
Create project-specific AWS account

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#232]
From @zaro0508 on May 27:

> Dear AWS Sandbox account users:

> As part of our effort to improve accounting and stability, Sage IT is deprecating the shared AWS Sandbox account in favor of other options such as individual sandbox accounts, team accounts and project accounts.  Our plan is to disable all Sandbox account access on July 4th 2022.  Please review the [cloud computing decision tree](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/2600239105/Computing+with+Amazon+Web+Services) to find the best option for your situation and contact IT if you require a new account.  We recommend that all users migrate their content from Sandbox to your chosen option before the above date. We hope that by collaborating early we can avoid any interruption to your work as Sandbox is taken away.  If you have further questions you can contact us via email or in the slack #sageit channel.  Thank you.

## Tasks

- [x] Read [Computing with Amazon Web Services](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/2600239105/Computing+with+Amazon+Web+Services)
- [x] Read [Bootstrapping AWS Project Accounts](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/2058878986/Bootstrapping+AWS+Project+Accounts)
- [x] Review [list of existing AWS accounts](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/352976898/Infrastructure+Inventory)
- [x] Identify the AWS account to use to deploy the dev, staging and production instance of the challenge stack (challenge registry, challenge platform)
- [ ] #274

**Comment by tschaffter** [comment]
## TODO

- Identify the AWS account to use to deploy the dev, staging and production instance of the challenge stack (challenge registry, challenge platform) (@tschaffter )

**Comment by tschaffter** [comment]
## Update

- I can login to the account as an Admin to the Cnb account

**Comment by tschaffter** [comment]
we now have the AWS account `CnbAccount`. For now there is no need to create another account to deploy the Challenge Registry stack.
