### ISSUE TITLE
Inventory Challenge Toolkit resources

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#255]
Add references to [Challenges - Documentation](https://docs.google.com/spreadsheets/d/1F2sFDgycvPdnLZD_lBd3qI9hKUSLQR7cVHRGwXyxmT8/edit#gid=0)

## Tasks

- [x] Search Sage Google shared drive
- [x] Search Sage GH repositories
- [ ] Add known and new manuscripts on ladder boot algorithms shared bt @echaibub

**Comment by tschaffter** [comment]
I have invited the member of the Slack channel #challenge to submit resources and documentation.

**Comment by tschaffter** [comment]
@echaibub

Hi Elias, are there recent manuscripts on Ladder Boot techniques that you think would be relevant before we start collecting use cases for the Challenge Toolkit? Thanks!

**Comment by tschaffter** [comment]
Shared by Elias:

Hi Thomas,

I went through the references of the original Ladder paper. Most of them are just either using it or arguing that it would be helpful to use it.

There are only a few methodology papers that built/extend upon it:

Zheng (2015) Toward a better understanding of leaderboard. arXiv:1510.03349. Proposes a simplification of the algorithm.

Hardt (2017) Climbing a shaky ladder: Better adaptive risk estimation. arXiv:1706.02733. Proposes an improved noisy version of the ladder.

Feldman (2019) The advantages of multiple classes for reducing overfitting from test set reuse. Shows how multiclass classifiers are less prone to overfitting than binary classifiers. (All theoretical results in the original ladder paper and the above two papers are based on binary classification.)

All the above papers provide theoretical guarantees that their algorithms will avoid overfitting of the public leaderboard. But, unfortunately, they only work when the public leaderboard holdout set is large … They do not work in small datasets …

Another algorithm that we could use if we have large datasets is the Thresholdout algorithm (Dwork et al. 2015. The reusable holdout: Preserving validity in adaptive data analysis. Science, 349(6248):636-638.) This algorithm, again, comes with theoretical guarantees and has been extended to work with AUROC metrics.

I also found a very interesting paper (Roelofs et 2019. A meta-analysis of overfitting in machine learning) with presents an empirical analysis of 120 Kaggle competitions and does not find strong evidence of overfitting to the public leaderboard. (And, therefore, suggests that standard practices we already use might work fine in practice …)
