### ISSUE TITLE
[Epic] Update Dev Environment tools 2024

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#2581]
### What product(s) is this story for?

Sage Monorepo

### Tasks

- [x] #2584
- [x] #2582
- [x] #2583
- [ ] update Node.js dependencies
- [ ] update the dev container tools
- [ ] migrate from yarn 2 to pnpm

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.
