### ISSUE TITLE
[Story] Edit User Profile

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#609]
Story: As a User, I want to be able to edit my profile information, so that I can manage the information I shared about me.

## Tasks

- [ ] Create placeholder component to edit user profile
- [ ] Show user profile edit component when clicking on `Edit Profile` button
- [ ] Create component to edit basic info about the user

**Comment by tschaffter** [comment]
Added to Spring 22.09

**Comment by tschaffter** [comment]
Added to Sprint 22.10 (October). Starting to work on the other pages before the next demo has highest priority.
