### ISSUE TITLE
Evaluate Gource - a software version control visualization tool

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#854]
I want to evaluate whether Gource can generate a visualization of the activity in this repository and whether this visualization can be used for the sake of reporting, e.g. at the end of a sprint, as well as to showcase the project in a fun way.

## Tasks

- [x] Identify how to run and interact with Gource visualization
- [ ] Identify how to programmatically generate a Gource visualization that is useful for reporting
- [ ] Identify how to automatically generate and publish the Gource visualization at the end of each sprint (optional)

**Comment by tschaffter** [comment]
## Gource implementations

- https://github.com/acaudwell/Gource
  - Official repo
- https://github.com/utensils/Envisaged
  - Dockerized Gource
- [Cartoonman/Envisaged-Redux](https://github.com/Cartoonman/Envisaged-Redux)
  - Fork of utensils/Envisaged
  - [GitLab](https://gitlab.com/Cartoonman/Envisaged-Redux)
  - [Docs](https://envisaged-redux.vercel.app/)
  - [Docker image](https://hub.docker.com/r/cartoonman/envisaged-redux)

**Comment by tschaffter** [comment]
## Identify how to run and interact with Gource visualization

Install `gource` on macOS:

```console
brew install gource
```

**Comment by tschaffter** [comment]
## Identify how to programmatically generate a Gource visualization that is useful for reporting

- Current Gource version: 0.53
- Gource version used by [utensils/Envisaged](https://github.com/utensils/Envisaged): ?
- Gource version used by [Cartoonman/Envisaged-Redux](https://github.com/Cartoonman/Envisaged-Redux): 0.51

**Comment by tschaffter** [comment]
The most user-friendly and flexible implementation of Gource is https://gitlab.com/Cartoonman/Envisaged-Redux
