### ISSUE TITLE
Explore Terms and Conditions page with Keycloak

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#898]
Specifications:

- [x] The user must agree with the Terms and Conditions before finalizing the user account creation.
- [ ] Ideally we want a static link to the Terms and Conditions so that this page can be reviewed by the user anytime.
  - The link to the terms and conditions used with KC is not static.
  - There may be a workaround (see comment below).
- [x] Prompt existing users to accept updated terms and conditions.

Keycloak can be configured to request the user to access the Terms and Conditions if we decide to use Keycloak for the registration process. The registration method is being discussed in #892.

## Tasks

- [x] Identify how to enable the Terms and Conditions page with Keycloak (standalone).
- [x] Identify how to enable the Terms and Conditions page with Keycloak (embedded).
- [x] Identify whether we can get a static link to the Terms and Conditions page.
  - Not possible (see below)

## Resources

- [Keycloak term and condition as a seperate page](https://stackoverflow.com/questions/51631836/keycloak-term-and-condition-as-a-seperate-page)
- #749
- https://www.keycloak.org/docs/19.0.3/server_development/index.html#_themes
- https://www.keycloak.org/docs/19.0.3/server_development/index.html#terms

**Comment by tschaffter** [comment]
## Enable Terms and Conditions with Keycloak

**Comment by tschaffter** [comment]
Lets explore Keycloak themes. First, lets enter the Keycloak docker container:

```console
docker exec -it challenge-keycloak bash
```

Enters the `themes` folder:

```console
$ cd /opt/keycloak/themes/

$ ls -al
total 4
drwxrwxr-x 2 keycloak root   23 Oct 26 15:31 .
drwxr-xr-x 1 keycloak root   29 Nov 18 04:57 ..
-rw-rw-r-- 1 keycloak root 1285 Oct  6 11:49 README.md
```

Instead of editing files from inside the KC container, we stop the container and restart it while mounting a local folder `themes`. This way we can edit the themes in VS Code.

**Comment by tschaffter** [comment]
## Terms and Conditions link

This link is not static and so we can not use it as is: http://localhost:8080/realms/test/login-actions/required-action?execution=terms_and_conditions&client_id=test-client&tab_id=M-PUcce1hlk

**Comment by tschaffter** [comment]
## Terms and Conditions and Embedded Keycloak

See this [example](https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server/tree/master/embedded-keycloak-server-custom/src/main/resources/theme/demo/login)
